
COLUMNS = [
    "Product ID",
    "SKU",
    "Collection",
    "Series",
    "Artwork Name",
    "Version",
    "Status",
    "Launch Date",
    "Last Updated",
    "Theme",
    "Primary Subject",
    "Secondary Subject",
    "Sacred Symbol",
    "Symbol Meaning",
    "Interior Style",
    "Art Style",
    "Mood",
    "Color Palette",
    "Border Style",
    "Texture",
    "Lighting",
    "Composition",
    "Complexity",
    "Master Prompt",
    "Image Prompt",
    "Negative Prompt",
    "Variation Prompt",
    "Upscale Prompt",
    "Editing Prompt",
    "Mockup Prompt",
    "Hero Image Prompt",
    "Thumbnail Prompt",
    "Print Sizes",
    "DPI",
    "Aspect Ratio",
    "File Formats",
    "SEO Title",
    "Short Title",
    "Meta Description",
    "Full Description",
    "13 Tags",
    "Category",
    "Materials",
    "Primary Keyword",
    "Secondary Keywords",
    "Room Suggestions",
    "Price",
    "Pinterest Title",
    "Pinterest Description",
    "Instagram Caption",
    "Facebook Caption",
    "Email Announcement",
    "Thank You Note",
    "Printing Guide",
    "License",
    "AI Disclosure",
    "Views",
    "Favorites",
    "Sales",
    "Revenue",
    "Conversion Rate",
    "SEO Score",
    "Thumbnail Score",
    "Artwork Score",
    "Brand Score",
    "Originality Score",
    "Overall Score",
    "Notes"
]
